baseURL = "https://iktinoz.github.io/"
languageCode = "en-us"
title = "Iktinoz"
theme = 'nightfall'
  

[params]
author = "iktinoz"
user = "iktinoz"
hostname = "github.io"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/iktinoz"


[[params.social]]
key = 1
name = "last.fm"
url = "https://www.last.fm/de/user/dernex"